# Compare Benchmark Runs
**Source:** Based on the example [compare-hypothesis.ipynb](https://github.com/Kotlin/kotlinx-benchmark/blob/master/examples/compare-hypothesis.ipynb) of the `kotlinx-benchmark` repository.

Grabs the last two runs and compares their score.

In [430]:
%use serialization, dataframe, kandy

In [431]:
@Serializable
public data class Benchmark(
    public val benchmark: String,
    public val mode: String,
    public val warmupIterations: Int,
    public val warmupTime: String,
    public val measurementIterations: Int,
    public val measurementTime: String,
    public val primaryMetric: PrimaryMetric,
    public val secondaryMetrics: Map<String, PrimaryMetric>,
    public val params: JsonObject? = null
)

@Serializable
public data class PrimaryMetric(
    public val score: Double,
    public val scoreError: Double,
    public val scoreConfidence: List<Double>,
    public val scorePercentiles: Map<String, Double>,
    public val scoreUnit: String,
    public val rawData: List<List<Double>>,
)

In [432]:
val nameLookupMap = mapOf(
    Pair("io.karpfen.features.BaseLineBenchmark.run", "Baseline"),
    Pair("io.karpfen.features.TogglePointOverheadBenchmark.run","Toggle-point"),
    Pair("io.karpfen.features.runtime.TickByTickOverhead.idle", "Tick-by-tick (idle)"),
    Pair("io.karpfen.features.runtime.BreakpointOverhead.idle", "Breakpoint (idle)"),
    Pair("io.karpfen.features.runtime.EventReplayOverhead.idle", "Event replay (idle)"),
    Pair("io.karpfen.features.runtime.EventReplayRecordingOverhead.record", "Event replay (recording)"),
    Pair("io.karpfen.features.runtime.EventReplayInjectionOverhead.inject", "Event replay (injection)"),
    Pair("io.karpfen.features.language.HistoryOverhead.idle", "History (idle)"),
    Pair("io.karpfen.features.language.TickLimitOverhead.idle", "Tick limit (idle)"),
    Pair("io.karpfen.features.language.TickLimitOverheadSpecializedNotSupported.notSupported", "Tick limit customized (workaround)"),
    Pair("io.karpfen.features.language.TickLimitOverheadSpecializedSupported.supported", "Tick limit customized (native)"),
    Pair("io.karpfen.features.language.HistoryOverheadSpecializedNotSupported.notSupported", "History customized (workaround)"),
    Pair("io.karpfen.features.language.HistoryOverheadSpecializedSupported.supported", "History customized (native)"),
)

In [433]:
//Fetch the last n benchmarks to include in the diagrams
val benchmarkCount = 2

In [434]:
import java.nio.file.Files
import java.nio.file.attribute.BasicFileAttributes
import kotlin.io.path.exists
import kotlin.io.path.forEachDirectoryEntry
import kotlin.io.path.isDirectory
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.readText

val runsDir = notebook.workingDir.resolve("../../../build/reports/benchmarks/main")
val outputFiles = runsDir.listDirectoryEntries()
    .filter { it.isDirectory() }
    .sortedByDescending { dir -> Files.readAttributes(dir, BasicFileAttributes::class.java).creationTime() }
    .subList(0, benchmarkCount)
    .map { it.resolve("benchmark.json") }

In [435]:
val json = Json { ignoreUnknownKeys = true }
val runs: List<List<Benchmark>> = outputFiles.map { file ->
    json.decodeFromString<List<Benchmark>>(file.readText())
}

In [436]:
import kotlinx.serialization.json.encodeToJsonElement
import org.jetbrains.letsPlot.core.plot.base.DataFrame

var combinedDf = emptyDataFrame<Benchmark>()
for (run in runs) {
    combinedDf = combinedDf.concat(run.toDataFrame() {
        "benchmark" from { nameLookupMap[it.benchmark] ?: it.benchmark }
        "score" from { it.primaryMetric.score }
        "scoreError" from { it.primaryMetric.scoreError }
        "deviationMin" from { it.primaryMetric.score - it.primaryMetric.scoreError }
        "deviationMax" from { it.primaryMetric.score + it.primaryMetric.scoreError }
    })
}
combinedDf = combinedDf.groupBy("benchmark").mean()
combinedDf

benchmark,score,scoreError,deviationMin,deviationMax
Tick limit customized (workaround),"3,946975","0,059992","3,886983","4,006967"
Tick limit customized (native),"2,405210","0,050416","2,354795","2,455626"

In [437]:
val minScore = combinedDf["deviationMin"].values().map { (it as Number).toDouble() }.minOrNull() ?: 0.0
val maxScore = combinedDf["deviationMax"].values().map { (it as Number).toDouble() }.maxOrNull() ?: 0.0

val lowerBound = minScore * 0.99
val upperBound = maxScore * 1.01

val plot = combinedDf.sortBy {"score".desc()}.plot {
    bars {
        x("benchmark")
        y("score") {
            scale = continuous(lowerBound..upperBound)
        }
    }
    errorBars {
        x("benchmark")
        yMin("deviationMin")
        yMax("deviationMax")
        width = 0.2
        borderLine.color = Color.BLACK
        borderLine.width = 0.75
    }
    coordinatesTransformation = CoordinatesTransformation.cartesianFlipped()
    layout {
        this.xAxisLabel = ""
        this.yAxisLabel = "ms/1000 ticks"
        style {
            global {
                title {
                    margin(10.0, -10.0)
                }
                text {
                    fontFamily = FontFamily.MONO
                }
            }
        }
        // Adjust the height of the Kandy plot based on the number of tests.
        size = 700 to ((50 * combinedDf.size().nrow) + 100)
    }
}
DISPLAY(HTML("<h4>Comparison</h4>"))
DISPLAY(plot)

In [438]:
val baseline = combinedDf["score"].values().map { (it as Number).toDouble() }.minOrNull()?: 0.0

var percentageDiffDf = combinedDf.mapToFrame {
    "benchmark" from { it.benchmark }
    "percentageDiff" from { (it.score - baseline) / baseline * 100 + 100}
    "percentageDeviationMin" from { (it.score - it.scoreError - baseline) / baseline * 100 + 100}
    "percentageDeviationMax" from { (it.score + it.scoreError - baseline) / baseline * 100 + 100}
}

percentageDiffDf

benchmark,percentageDiff,percentageDeviationMin,percentageDeviationMax
Tick limit customized (workaround),"164,101048","161,606792","166,595304"
Tick limit customized (native),"100,000000","97,903902","102,096098"

In [439]:
val minScore = percentageDiffDf["percentageDeviationMin"].values().map { (it as Number).toDouble() }.minOrNull() ?: 0.0
val maxScore = percentageDiffDf["percentageDeviationMax"].values().map { (it as Number).toDouble() }.maxOrNull() ?: 0.0

val lowerBound = minScore * 0.99
val upperBound = maxScore * 1.01

val plot = percentageDiffDf.sortBy {"percentageDiff".desc()}.plot {
    bars {
        x("benchmark")
        y("percentageDiff") {
            scale = continuous(lowerBound..upperBound)
            axis.breaks(format = "{.1f}%")
        }
    }
    errorBars {
        x("benchmark")
        yMin("percentageDeviationMin")
        yMax("percentageDeviationMax")
        width = 0.2
        borderLine.color = Color.BLACK
        borderLine.width = 0.75
    }
    coordinatesTransformation = CoordinatesTransformation.cartesianFlipped()
    layout {
        this.xAxisLabel = ""
        this.yAxisLabel = ""
        style {
            global {
                title {
                    margin(10.0, -10.0)
                }
                text {
                    fontFamily = FontFamily.MONO
                }
            }
        }
        // Adjust the height of the Kandy plot based on the number of tests.
        size = 700 to ((50 * combinedDf.size().nrow) + 100)
    }
}
DISPLAY(HTML("<h4>Comparison</h4>"))
DISPLAY(plot)