# Compare Benchmark Runs
**Source:** Based on the example [compare-hypothesis.ipynb](https://github.com/Kotlin/kotlinx-benchmark/blob/master/examples/compare-hypothesis.ipynb) of the `kotlinx-benchmark` repository.

Grabs the last two runs and compares their score.

In [41]:
%use serialization, dataframe, kandy

In [42]:
@Serializable
public data class Benchmark(
    public val benchmark: String,
    public val mode: String,
    public val warmupIterations: Int,
    public val warmupTime: String,
    public val measurementIterations: Int,
    public val measurementTime: String,
    public val primaryMetric: PrimaryMetric,
    public val secondaryMetrics: Map<String, PrimaryMetric>,
    public val params: JsonObject? = null
)

@Serializable
public data class PrimaryMetric(
    public val score: Double,
    public val scoreError: Double,
    public val scoreConfidence: List<Double>,
    public val scorePercentiles: Map<String, Double>,
    public val scoreUnit: String,
    public val rawData: List<List<Double>>,
)

In [43]:
val nameLookupMap = mapOf(
    Pair("io.karpfen.features.BaseLineBenchmark.run", "Base-line"),
    Pair("io.karpfen.features.TogglePointOverheadBenchmark.run","Toggle-point overhead"),
    Pair("io.karpfen.features.runtime.TickByTickOverhead.idle", "Tick-by-tick overhead (idle)"),
    Pair("io.karpfen.features.runtime.BreakpointOverhead.idle", "Breakpoint overhead (idle)"),
    Pair("io.karpfen.features.runtime.EventReplayOverhead.idle", "Event replay overhead (idle)"),
    Pair("io.karpfen.features.runtime.EventReplayRecordingOverhead.record", "Event replay overhead (recording)"),
    Pair("io.karpfen.features.runtime.EventReplayInjectionOverhead.inject", "Event replay overhead (injection)"),
    Pair("io.karpfen.features.language.HistoryOverhead.idle", "History overhead (idle)"),
    Pair("io.karpfen.features.language.TickLimitOverhead.idle", "Tick limit overhead (idle)"),
    Pair("io.karpfen.features.language.TickLimitOverheadSpecializedNotSupported.notSupported", "Tick limit overhead (specialized) (not supported)"),
    Pair("io.karpfen.features.language.TickLimitOverheadSpecializedSupported.supported", "Tick limit overhead (specialized) (supported)"),
    Pair("io.karpfen.features.language.HistoryOverheadSpecializedNotSupported.notSupported", "History overhead (specialized) (not supported)"),
    Pair("io.karpfen.features.language.HistoryOverheadSpecializedSupported.supported", "History overhead (specialized) (supported)"),
)

In [44]:
val benchmarkCount = 1

In [45]:
import java.nio.file.Files
import java.nio.file.attribute.BasicFileAttributes
import kotlin.io.path.exists
import kotlin.io.path.forEachDirectoryEntry
import kotlin.io.path.isDirectory
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.readText

val runsDir = notebook.workingDir.resolve("../../../build/reports/benchmarks/main")
val outputFiles = runsDir.listDirectoryEntries()
    .filter { it.isDirectory() }
    .sortedByDescending { dir -> Files.readAttributes(dir, BasicFileAttributes::class.java).creationTime() }
    .subList(0, benchmarkCount)
    .map { it.resolve("benchmark.json") }
outputFiles

[C:\Users\fabio\Desktop\Programmieren\karpfenProject\karpfenRuntime\execution-engine\src\benchmark\kotlin\..\..\..\build\reports\benchmarks\main\2026-07-26T11.52.19.9647709\benchmark.json]

In [46]:
val json = Json { ignoreUnknownKeys = true }
val runs: List<List<Benchmark>> = outputFiles.map { file ->
    json.decodeFromString<List<Benchmark>>(file.readText())
}

In [47]:
import kotlinx.serialization.json.encodeToJsonElement
import org.jetbrains.letsPlot.core.plot.base.DataFrame

var combinedDf = emptyDataFrame<Benchmark>()
for (run in runs) {
    combinedDf = combinedDf.concat(run.toDataFrame() {
        "benchmark" from { nameLookupMap[it.benchmark] ?: it.benchmark }
        "score" from { it.primaryMetric.score }
        "scoreError" from { it.primaryMetric.scoreError }
        "deviationMin" from { it.primaryMetric.score - it.primaryMetric.scoreError }
        "deviationMax" from { it.primaryMetric.score + it.primaryMetric.scoreError }
    })
}
combinedDf = combinedDf.groupBy("benchmark").mean()
combinedDf

benchmark,score,scoreError,deviationMin,deviationMax
Toggle-point overhead,"8,480399","0,083615","8,396784","8,564014"
History overhead (idle),"8,670102","0,062697","8,607405","8,732799"
History overhead (specialized) (not s...,"6,092588","0,101260","5,991328","6,193848"
History overhead (specialized) (suppo...,"3,788612","0,058396","3,730216","3,847007"
Tick limit overhead (idle),"431,104449","1639,097819","-1207,993369","2070,202268"
Tick limit overhead (specialized) (no...,"7,297168","0,036538","7,260630","7,333706"
Tick limit overhead (specialized) (su...,"2,357402","0,009607","2,347796","2,367009"
Breakpoint overhead (idle),"9,145020","0,048554","9,096466","9,193573"
Event replay overhead (injection),"9,052296","0,037157","9,015139","9,089453"
Event replay overhead (idle),"16,467014","30,135963","-13,668950","46,602977"
Event replay overhead (recording),"9,807433","4,042894","5,764539","13,850327"
Tick-by-tick overhead (idle),"8,880722","0,198334","8,682387","9,079056"

In [48]:
val minScore = combinedDf["deviationMin"].values().map { (it as Number).toDouble() }.minOrNull() ?: 0.0
val maxScore = combinedDf["deviationMax"].values().map { (it as Number).toDouble() }.maxOrNull() ?: 0.0

val lowerBound = minScore * 0.99
val upperBound = maxScore * 1.01

val plot = combinedDf.sortBy {"score".desc()}.plot {
    bars {
        x("benchmark")
        y("score") {
            scale = continuous(lowerBound..upperBound)
        }
    }
    errorBars {
        x("benchmark")
        yMin("deviationMin")
        yMax("deviationMax")
        width = 0.2
        borderLine.color = Color.BLACK
        borderLine.width = 0.75
    }
    coordinatesTransformation = CoordinatesTransformation.cartesianFlipped()
    layout {
        this.xAxisLabel = ""
        this.yAxisLabel = "ms/1000 ticks"
        style {
            global {
                title {
                    margin(10.0, -10.0)
                }
                text {
                    fontFamily = FontFamily.MONO
                }
            }
        }
        // Adjust the height of the Kandy plot based on the number of tests.
        size = 700 to ((50 * combinedDf.size().nrow) + 100)
    }
}
DISPLAY(HTML("<h4>Comparison</h4>"))
DISPLAY(plot)

In [49]:
val baseline = combinedDf["score"].values().map { (it as Number).toDouble() }.minOrNull()?: 0.0

var percentageDiffDf = combinedDf.mapToFrame {
    "benchmark" from { it.benchmark }
    "percentageDiff" from { (it.score - baseline) / baseline * 100 + 100}
    "percentageDeviationMin" from { (it.score - it.scoreError - baseline) / baseline * 100 + 100}
    "percentageDeviationMax" from { (it.score + it.scoreError - baseline) / baseline * 100 + 100}
}

percentageDiffDf

benchmark,percentageDiff,percentageDeviationMin,percentageDeviationMax
Toggle-point overhead,"359,734904","356,187995","363,281812"
History overhead (idle),"367,782018","365,122435","370,441600"
History overhead (specialized) (not s...,"258,444978","254,149564","262,740391"
History overhead (specialized) (suppo...,"160,711289","158,234177","163,188402"
Tick limit overhead (idle),"18287,267100","-51242,564142","87817,098342"
Tick limit overhead (specialized) (no...,"309,542772","307,992850","311,092695"
Tick limit overhead (specialized) (su...,"100,000000","99,592492","100,407508"
Breakpoint overhead (idle),"387,927837","385,868203","389,987471"
Event replay overhead (injection),"383,994537","382,418362","385,570712"
Event replay overhead (idle),"698,523699","-579,831019","1976,878416"
Event replay overhead (recording),"416,027122","244,529274","587,524971"
Tick-by-tick overhead (idle),"376,716436","368,303174","385,129698"

In [50]:
val minScore = percentageDiffDf["percentageDeviationMin"].values().map { (it as Number).toDouble() }.minOrNull() ?: 0.0
val maxScore = percentageDiffDf["percentageDeviationMax"].values().map { (it as Number).toDouble() }.maxOrNull() ?: 0.0

val lowerBound = minScore * 0.99
val upperBound = maxScore * 1.01

val plot = percentageDiffDf.sortBy {"percentageDiff".desc()}.plot {
    bars {
        x("benchmark")
        y("percentageDiff") {
            scale = continuous(lowerBound..upperBound)
            axis.breaks(format = "{.1f}%")
        }
    }
    errorBars {
        x("benchmark")
        yMin("percentageDeviationMin")
        yMax("percentageDeviationMax")
        width = 0.2
        borderLine.color = Color.BLACK
        borderLine.width = 0.75
    }
    coordinatesTransformation = CoordinatesTransformation.cartesianFlipped()
    layout {
        this.xAxisLabel = ""
        this.yAxisLabel = "execution time increase"
        style {
            global {
                title {
                    margin(10.0, -20.0)
                }
                text {
                    fontFamily = FontFamily.MONO
                }
            }
        }
        // Adjust the height of the Kandy plot based on the number of tests.
        size = 800 to ((50 * combinedDf.size().nrow) + 100)
    }
}
DISPLAY(HTML("<h4>Comparison</h4>"))
DISPLAY(plot)